### PR TITLE
Add syntax-dynamic-import babel plugin

### PR DESCRIPTION
**Pull request by ziir**
Required for https://webpack.js.org/guides/code-splitting/#dynamic-imports

### CODE REVIEW

**Comment by pascalduez** [comment]
Our unit tests will fail though, they will need another plugin such as [babel-plugin-dynamic-import-node](https://github.com/airbnb/babel-plugin-dynamic-import-node).

**Comment by ziir** [comment]
So, unit tests are indeed failing.

My understanding is that we need `dynamic-import-node` only for the tests and `syntax-dynamic-import` for packaging.

Digging a little further.

**Comment by ziir** [comment]
More on this:

### src
```js
function getComponent() {
  return import(
    /* webpackChunkName: "SingleDatePicker" */
    'react-dates/lib/components/SingleDatePicker'
  );
}
```

### esm | dist build
```js
function getComponent() {
  return import(/* webpackChunkName: "SingleDatePicker" */'react-dates/lib/components/SingleDatePicker');
}
```

### tests
```js
function getComponent() {
  return Promise.resolve().then(function () {
    return require('react-dates/lib/components/SingleDatePicker');
  });
}
```

**Comment by ziir** [comment]
So, one drawback of using the `import()` syntax in a library is that you need to re-compile this lib when running tests from a consumer of this lib. Am struggling a little with that at the moment but almost there.

**Comment by pascalduez** [comment]
Merging, will be useful (in apps :)

**Pull request merged**
