### PR TITLE
Switch to Babel preset latest

### PR DESCRIPTION
**Pull request by pascalduez**
Docs:
https://babeljs.io/docs/plugins/preset-latest/

RFC.

### CODE REVIEW

**Comment by ziir** [comment]
I fail to see what' in it for us?

Have you checked 'do expressions' though ?

**Comment by pascalduez** [comment]
The `do {}` expression is not included there, it's a stage-0 proposal. 
I would be for adding it though (another topic).  

The `es2017` preset includes the two plugins we are already using:
`syntax-trailing-function-commas`
`transform-async-to-generator`

It's definitely not a much required change, just nicer (IMO) and apparently more in sync with what the Babel project recommends and lean toward.

**Comment by ziir** [comment]
I'm fine with using the `es2017` preset and removing the now duplicate plugins from our package.json

The `latest` preset includes the `es2016` preset, which we have no use for AFAIK:
transform-exponentiation-operator https://babeljs.io/docs/plugins/transform-exponentiation-operator/

So I'd be more inclined to add the `es2017` preset and add specific plugins (or presets) we actually want to use rather than including a bunch of stuff we don't need just because it is more convient or feels cleaner.

**Comment by pascalduez** [comment]
> bunch of stuff we don't need

The `es2016` preset has only one plugin.

If we add just the `es2017` we still need the `es1025`.  

If we want fine control over which plugins to include then we should even not use the `es2105`, this one includes a bunch of stuff.

It's not about being convenient or whatever, more about following ES versions, so that it makes sense.
Agree we should still keep on eye on it to control if it's not going to crazy though.

**Comment by ziir** [comment]
> The es2016 preset has only one plugin.
True, we don't know about the future es2018 preset, and it's already one too many :)

> If we add just the es2017 we still need the es1025.
Yup,

> If we want fine control over which plugins to include then we should even not use the es2105, this one includes a bunch of stuff.
If there are some plugins that we don't use, then yes, I believe we should not use it

> It's not about being convenient or whatever, more about following ES versions, so that it makes sense.
We can always document which plugins is linked to which "ES version"

**Comment by pascalduez** [comment]
>  it's already one too many

I can make you a list of all the crap we install and load without even needed/using it :)

Anyway, this is just a RFC to gather feedback. If it does not make consensus I would leave things as they are: `es2015` plus granularly selected plugins of the things we use.

**Comment by pascalduez** [comment]
Closing, I will make another PR with the `babel-preset-env` which is far superior. 
No hurry though.

**Pull request closed without merging**
